#!/bin/bash

# 🎀  Get the IP address.
ping bean.local  # 🎀 Note to self: 172.20.10.14

# 🎀 Log in with SSH.
ssh bean@bean.local  # 🎀 or ssh bean@<IP-you-found>

# 🎀 Run on first boot.
sudo raspi-config nonint do_i2c 0
sudo raspi-config nonint do_spi 0
sudo raspi-config nonint do_boot_wait 0
sudo apt update && sudo apt full-upgrade -y
sudo reboot

# 🎀 Set the Python environment.
sudo apt install -y python3-venv git python3-dev libevdev-dev portaudio19-dev
python3 -m venv ~/bean-env
echo 'source ~/bean-env/bin/activate' >> ~/.bashrc
source ~/.bashrc
pip install --upgrade pip wheel
pip install openai elevenlabs gpiozero sounddevice pillow python-dotenv evdev
