#!/bin/bash

# 🎀 ---------- Preferred method ----------

# 🎀 Install dependencies.
sudo apt install -y python3-pip libpython3-dev libdbus-1-dev python3-dbus network-manager build-essential

# 🎀 Grab the latest eduroam installer.
# 🎀 If the link doesn't work (ERROR 500: Internal Server Error), go to https://cat.eduroam.org, navigate to the Linux download page for your uni, and get the link in the Network tab in the Web Inspector in Safari.
wget -L -O eduroam_UoC.py "https://cat.eduroam.org/user/API.php?action=downloadInstaller&lang=en&profile=523&device=linux&generatedfor=user&openroaming=0"

# 🎀 Run it.
sudo mkdir -p /root/.config
sudo python3 eduroam_UoC.py
sudo nmcli connection up eduroam

# 🎀 ---------- ONLY use this if all else fails use this cos manual cert paths can be fragile... ----------

# 🎀 Manual control
network={
    ssid="eduroam"
    key_mgmt=WPA-EAP
    eap=TTLS
    identity="abc123+pi2025@cam.ac.uk"
    password="TOKEN_PASSWORD"
    phase2="auth=PAP"
    altsubject_match="DNS:radius01.wifi.cam.ac.uk"
    ca_cert="/etc/ssl/certs/USERTrust_Root_CA.pem"
}
sudo wpa_cli reconfigure
