#!/bin/bash

# 🎀 ---------- Method 1 ----------

# 🎀 Install dependencies.
sudo apt install -y python3-pip libpython3-dev libdbus-1-dev python3-dbus network-manager build-essential

# 🎀 Grab the latest eduroam installer.
# 🎀 If the link doesn't work (ERROR 500: Internal Server Error), go to https://cat.eduroam.org, navigate to the Linux download page for your uni, and get the link in the Network tab in the Web Inspector in Safari.
wget -L -O eduroam_UoC.py "https://cat.eduroam.org/user/API.php?action=downloadInstaller&lang=en&profile=523&device=linux&generatedfor=user&openroaming=0"

# 🎀 Run it.
sudo mkdir -p /root/.config
sudo python3 eduroam_UoC.py
sudo nmcli connection up eduroam

# 🎀 ---------- Method 2 ----------

# 🎀 Setup.
sudo nmcli connection add \
   type wifi ifname wlan0 con-name eduroam ssid eduroam \
   -- \
   wifi-sec.key-mgmt wpa-eap 802-1x.eap ttls 802-1x.phase2-auth pap \
   802-1x.identity "CRSID+DEVICE@cam.ac.uk" \
   802-1x.password "TOKEN_PASSWORD" \
   connection.autoconnect yes \
   connection.autoconnect-priority 20

# 🎀 Set "Preconfigured" to fallback.
sudo nmcli connection modify preconfigured connection.autoconnect-priority 5
